# Copyright (C) 2017-2021 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/j3x3g/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/j3x3g/proprietary/bin/batterysrv:system/bin/batterysrv \
    vendor/samsung/j3x3g/proprietary/bin/calibration_init:system/bin/calibration_init \
    vendor/samsung/j3x3g/proprietary/bin/charge:system/bin/charge \
    vendor/samsung/j3x3g/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/j3x3g/proprietary/bin/connfwexe:system/bin/connfwexe \
    vendor/samsung/j3x3g/proprietary/bin/cp_diskserver:system/bin/cp_diskserver \
    vendor/samsung/j3x3g/proprietary/bin/ddexe:system/bin/ddexe \
    vendor/samsung/j3x3g/proprietary/bin/download:system/bin/download \
    vendor/samsung/j3x3g/proprietary/bin/drsd:system/bin/drsd \
    vendor/samsung/j3x3g/proprietary/bin/engpc:system/bin/engpc \
    vendor/samsung/j3x3g/proprietary/bin/ext_symlink.sh:system/bin/ext_symlink.sh \
    vendor/samsung/j3x3g/proprietary/bin/macloader:system/bin/macloader \
    vendor/samsung/j3x3g/proprietary/bin/mfgloader:system/bin/mfgloader \
    vendor/samsung/j3x3g/proprietary/bin/modem_control:system/bin/modem_control \
    vendor/samsung/j3x3g/proprietary/bin/modemd:system/bin/modemd \
    vendor/samsung/j3x3g/proprietary/bin/npsmobex:system/bin/npsmobex \
    vendor/samsung/j3x3g/proprietary/bin/phoneserver:system/bin/phoneserver \
    vendor/samsung/j3x3g/proprietary/bin/prepare_param.sh:system/bin/prepare_param.sh \
    vendor/samsung/j3x3g/proprietary/bin/refnotify:system/bin/refnotify \
    vendor/samsung/j3x3g/proprietary/bin/wcnd:system/bin/wcnd \
    vendor/samsung/j3x3g/proprietary/bin/wlandutservice:system/bin/wlandutservice \
    vendor/samsung/j3x3g/proprietary/cameradata/datapattern_420sp.yuv:system/cameradata/datapattern_420sp.yuv \
    vendor/samsung/j3x3g/proprietary/cameradata/datapattern_front_420sp.yuv:system/cameradata/datapattern_front_420sp.yuv \
    vendor/samsung/j3x3g/proprietary/etc/connectivity_calibration.ini:system/etc/connectivity_calibration.ini \
    vendor/samsung/j3x3g/proprietary/etc/connectivity_configure.ini:system/etc/connectivity_configure.ini \
    vendor/samsung/j3x3g/proprietary/etc/firmware/sc2331_fdl.bin:system/etc/firmware/sc2331_fdl.bin \
    vendor/samsung/j3x3g/proprietary/etc/firmware/sc2331_fw.bin:system/etc/firmware/sc2331_fw.bin \
    vendor/samsung/j3x3g/proprietary/etc/thermalSensorsConfig.xml:system/etc/thermalSensorsConfig.xml \
    vendor/samsung/j3x3g/proprietary/etc/wifi/p2p_supplicant_overlay.conf:system/etc/wifi/p2p_supplicant_overlay.conf \
    vendor/samsung/j3x3g/proprietary/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
    vendor/samsung/j3x3g/proprietary/etc/wifi/wpa_supplicant_overlay.conf:system/etc/wifi/wpa_supplicant_overlay.conf \
    vendor/samsung/j3x3g/proprietary/lib/hw/camera.sc8830.so:system/lib/hw/camera.sc8830.so \
    vendor/samsung/j3x3g/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/samsung/j3x3g/proprietary/lib/hw/sensors.sc8830.so:system/lib/hw/sensors.sc8830.so \
    vendor/samsung/j3x3g/proprietary/lib/libAF.so:system/lib/libAF.so \
    vendor/samsung/j3x3g/proprietary/lib/libQjpeg.so:system/lib/libQjpeg.so \
    vendor/samsung/j3x3g/proprietary/lib/libQmageDecoder.so:system/lib/libQmageDecoder.so \
    vendor/samsung/j3x3g/proprietary/lib/lib_SamsungRec_V04013.so:system/lib/lib_SamsungRec_V04013.so \
    vendor/samsung/j3x3g/proprietary/lib/lib_Samsung_Resampler.so:system/lib/lib_Samsung_Resampler.so \
    vendor/samsung/j3x3g/proprietary/lib/lib_Samsung_SB_AM_for_ICS_v04004.so:system/lib/lib_Samsung_SB_AM_for_ICS_v04004.so \
    vendor/samsung/j3x3g/proprietary/lib/libae.so:system/lib/libae.so \
    vendor/samsung/j3x3g/proprietary/lib/libaf_running.so:system/lib/libaf_running.so \
    vendor/samsung/j3x3g/proprietary/lib/libaf_tune.so:system/lib/libaf_tune.so \
    vendor/samsung/j3x3g/proprietary/lib/libatchannel.so:system/lib/libatchannel.so \
    vendor/samsung/j3x3g/proprietary/lib/libaudio-ril.so:system/lib/libaudio-ril.so \
    vendor/samsung/j3x3g/proprietary/lib/libawb.so:system/lib/libawb.so \
    vendor/samsung/j3x3g/proprietary/lib/libbm.so:system/lib/libbm.so \
    vendor/samsung/j3x3g/proprietary/lib/libboost.so:system/lib/libboost.so \
    vendor/samsung/j3x3g/proprietary/lib/libbt-aptx-4.0.3.so:system/lib/libbt-aptx-4.0.3.so \
    vendor/samsung/j3x3g/proprietary/lib/libbt-codec_aptx.so:system/lib/libbt-codec_aptx.so \
    vendor/samsung/j3x3g/proprietary/lib/libbt-codec_sshd.so:system/lib/libbt-codec_sshd.so \
    vendor/samsung/j3x3g/proprietary/lib/libbt-iopdb.so:system/lib/libbt-iopdb.so \
    vendor/samsung/j3x3g/proprietary/lib/libbt-iopdb_mod.so:system/lib/libbt-iopdb_mod.so \
    vendor/samsung/j3x3g/proprietary/lib/libbt-vendor.so:system/lib/libbt-vendor.so \
    vendor/samsung/j3x3g/proprietary/lib/libcalibration.so:system/lib/libcalibration.so \
    vendor/samsung/j3x3g/proprietary/lib/libcc_manager.so:system/lib/libcc_manager.so \
    vendor/samsung/j3x3g/proprietary/lib/libcharon.so:system/lib/libcharon.so \
    vendor/samsung/j3x3g/proprietary/lib/libdeflicker.so:system/lib/libdeflicker.so \
    vendor/samsung/j3x3g/proprietary/lib/libedmnativehelper.so:system/lib/libedmnativehelper.so \
    vendor/samsung/j3x3g/proprietary/lib/libefuse.so:system/lib/libefuse.so \
    vendor/samsung/j3x3g/proprietary/lib/libengbt.so:system/lib/libengbt.so \
    vendor/samsung/j3x3g/proprietary/lib/libfactoryutil.so:system/lib/libfactoryutil.so \
    vendor/samsung/j3x3g/proprietary/lib/libgpspc.so:system/lib/libgpspc.so \
    vendor/samsung/j3x3g/proprietary/lib/libhydra.so:system/lib/libhydra.so \
    vendor/samsung/j3x3g/proprietary/lib/libiwnpi.so:system/lib/libiwnpi.so \
    vendor/samsung/j3x3g/proprietary/lib/liblsc.so:system/lib/liblsc.so \
    vendor/samsung/j3x3g/proprietary/lib/libmaet.so:system/lib/libmaet.so \
    vendor/samsung/j3x3g/proprietary/lib/libmemoryheapion.so:system/lib/libmemoryheapion.so \
    vendor/samsung/j3x3g/proprietary/lib/libnvexchange.so:system/lib/libnvexchange.so \
    vendor/samsung/j3x3g/proprietary/lib/libomission_avoidance.so:system/lib/libomission_avoidance.so \
    vendor/samsung/j3x3g/proprietary/lib/libomx_avcdec_hw_sprd.so:system/lib/libomx_avcdec_hw_sprd.so \
    vendor/samsung/j3x3g/proprietary/lib/libomx_avcdec_sw_sprd.so:system/lib/libomx_avcdec_sw_sprd.so \
    vendor/samsung/j3x3g/proprietary/lib/libomx_avcenc_hw_sprd.so:system/lib/libomx_avcenc_hw_sprd.so \
    vendor/samsung/j3x3g/proprietary/lib/libomx_m4vh263dec_hw_sprd.so:system/lib/libomx_m4vh263dec_hw_sprd.so \
    vendor/samsung/j3x3g/proprietary/lib/libomx_m4vh263dec_sw_sprd.so:system/lib/libomx_m4vh263dec_sw_sprd.so \
    vendor/samsung/j3x3g/proprietary/lib/libomx_m4vh263enc_hw_sprd.so:system/lib/libomx_m4vh263enc_hw_sprd.so \
    vendor/samsung/j3x3g/proprietary/lib/libomx_mp3dec_sprd.so:system/lib/libomx_mp3dec_sprd.so \
    vendor/samsung/j3x3g/proprietary/lib/libomx_vpxdec_hw_sprd.so:system/lib/libomx_vpxdec_hw_sprd.so \
    vendor/samsung/j3x3g/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/j3x3g/proprietary/lib/libbinder.so:system/lib/libbinder.so \
    vendor/samsung/j3x3g/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/samsung/j3x3g/proprietary/lib/libreference-ril_sp.so:system/lib/libreference-ril_sp.so \
    vendor/samsung/j3x3g/proprietary/lib/librilutils.so:system/lib/librilutils.so \
    vendor/samsung/j3x3g/proprietary/lib/libsamsungRecord.so:system/lib/libsamsungRecord.so \
    vendor/samsung/j3x3g/proprietary/lib/libsamsungSoundbooster.so:system/lib/libsamsungSoundbooster.so \
    vendor/samsung/j3x3g/proprietary/lib/libseccamera_jni.so:system/lib/libseccamera_jni.so \
    vendor/samsung/j3x3g/proprietary/lib/libseccameracore.so:system/lib/libseccameracore.so \
    vendor/samsung/j3x3g/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/j3x3g/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/j3x3g/proprietary/lib/libsecure_storage.so:system/lib/libsecure_storage.so \
    vendor/samsung/j3x3g/proprietary/lib/libsft_af_ctrl.so:system/lib/libsft_af_ctrl.so \
    vendor/samsung/j3x3g/proprietary/lib/libspaf.so:system/lib/libspaf.so \
    vendor/samsung/j3x3g/proprietary/lib/libstlport.so:system/lib/libstlport.so \
    vendor/samsung/j3x3g/proprietary/lib/libstrongswan.so:system/lib/libstrongswan.so \
    vendor/samsung/j3x3g/proprietary/lib/libsxqk_skia.so:system/lib/libsxqk_skia.so \
    vendor/samsung/j3x3g/proprietary/lib/libvbeffect.so:system/lib/libvbeffect.so \
    vendor/samsung/j3x3g/proprietary/lib/libvbpga.so:system/lib/libvbpga.so \
    vendor/samsung/j3x3g/proprietary/lib/libynoise.so:system/lib/libynoise.so \
    vendor/samsung/j3x3g/proprietary/sbin/sswap:root/sbin/sswap \
    vendor/samsung/j3x3g/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    vendor/samsung/j3x3g/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    vendor/samsung/j3x3g/proprietary/vendor/lib/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib/mediadrm/libdrmclearkeyplugin.so \
    vendor/samsung/j3x3g/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so
